### ISSUE TITLE
Unable to generate crypto config

### ISSUE THREAD

**Issue by shalini-kad** [HyperledgerHandsOn/trade-finance-logistics#17]
Unable to generate crypto config and genesis block. Getting some error.
![screen shot 2018-07-11 at 11 45 32 pm](https://user-images.githubusercontent.com/34833306/42591552-a5983ac2-8564-11e8-8d08-e37d602a86a9.png)

**Comment by VRamakrishna** [comment]
This code was developed for the 1.1 version of Hyperledger Fabric. Just last week, a new version (1.2) was released, so if you cloned `fabric` and `fabric-ca` recently, you are going to get the 1.2 branch by default.

I suspect this is the cause of the error you are seeing. Can you clone the `release-1.1` branch of the Fabric repositories?
- https://github.com/hyperledger/fabric/tree/release-1.1
- https://github.com/hyperledger/fabric-ca/tree/release-1.1
Then rebuild the `configtxgen` and `cryptogen` tools, and retry the trade script using the instructions.

**Comment by VRamakrishna** [comment]
@shalini-kad If you scroll down the instructions in the [network](https://github.com/HyperledgerHandsOn/trade-finance-logistics/tree/master/network) folder, you'll see that the requirement to clone the `release-1.1` branch is clearly stated.
