### ISSUE TITLE
create-channel.js had required a path change

### ISSUE THREAD

**Issue by sahirvsahirv** [HyperledgerHandsOn/trade-finance-logistics#31]
I had to change it to

> var

 _commonProto = grpc.load(path.join(__dirname, '**../application/**node_modules/fabric-client/lib/protos/common/common.proto')).common;
var _configtxProto = grpc.load(path.join(__dirname, 

> '../application/node_modules/fabric-client/lib/protos/common/configtx.proto')).common;

to make it work. Please consider it if it is valid for all. Thanks

**Comment by sahirvsahirv** [comment]
hypledvm@hypledvm-VirtualBox:~/go/src/utilitypoc/application$ **node app.js**
info: [ClientUtils]: 

*******************************************************************************
*******************************************************************************
*                                          
* Using temp dir: ../network/client-certs
*                                          
*******************************************************************************
*******************************************************************************

/home/node_modules/grpc/index.js:146
  return loadObject(builder.ns, options);
                            ^

TypeError: Cannot read property 'ns' of null
    at Object.load (/home/node_modules/grpc/index.js:146:29)
    at Object.<anonymous> (/home/hypledvm/go/src/utilitypoc/middleware/create-channel.js:26:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hypledvm/go/src/utilitypoc/application/app.js:32:21)


Changing the directory here works

**Comment by VRamakrishna** [comment]
Did you follow the instructions in `middleware` and install the NPM modules _before_ trying to run the `application`? That's a prerequisite mentioned both in the instructions in this repo and in the chapter (where we walk through `middleware` before `application`.) This sequencing has a particular logic.

**Comment by VRamakrishna** [comment]
FYI, you need to run `npm install` in `middleware/`. But do sync the latest code though; I fixed dependency versions a few days ago (because the remote repository for the NPM packages got upgraded.)

**Comment by sahirvsahirv** [comment]
Probably I did not follow the same steps. But I had to change it to get
mine to work.

We can close it if not applicable for all.

**Comment by sahirvsahirv** [comment]
Thanks

**Comment by VRamakrishna** [comment]
Lastly, though I'd like to be helpful, especially to our book customers, I'm afraid I can't be addressing issues at this rate. I (like all the authors of this book) have a day job that keeps me busy. Maintaining this code base is strictly a side project for me.

So I'd encourage you to learn from the book and especially understand the rationale behind the steps performed. That'll help you sort out issues.

Of course, if you do find a real problem with the code or the instructions, file a bug report and we'll try to address it ASAP. But make sure you've exhausted your options first.

Thanks, and good luck!

**Comment by sahirvsahirv** [comment]
Thanks so much. I get that. We need proficiency in node and GO to and
docker to start with.

I am new to all the three and it has taught me quite a lot.

I have left office. Will update soon.

Thanks

**Comment by sahirvsahirv** [comment]
The other two that I had posted today, I had already solved by working my
way through.

I just posted it thinking that it might help others in the process not
because there was a bug in the book or code.

Probably it was the wrong forum.
Sorry for that.

Thanks so much.
Gowri

**Comment by VRamakrishna** [comment]
Not a problem. Even if you encounter issues with adaptations to other apps and other network structures because of inadequacies in our instructions, it's useful to bring them to our attention. But do note that we'll get to work on them on a best-effort basis.
