### ISSUE TITLE
How to get all the assets related with client?

### ISSUE THREAD

**Issue by bh4rtp** [HyperledgerHandsOn/trade-finance-logistics#33]
Now there are four org in the network. But as to every org, there are a number of entities. For each client, it should be assigned to a specified role and a specified identity, i.e. entity of exporter, importer, exporter bank, importer bank, regulator or carrier. If the client of a given importer wants to query all the assets of him, how to do it? It seems easy to identify the role but uneasy to identify the identity of the client.
And why set the identity when instantiating the chaincode? Does this mean there is only one instance for each role?
Thanks.

**Comment by VRamakrishna** [comment]
The view offered by the chaincode (in other words, the set of invoke and query functions) is the only means through which a client can get any information stored in the ledger. As you can see in the chaincode, we have defined a number of functions to query asset information, like `getTradeStatus`, `getLCStatus`, etc.

I'm guessing you are asking how a client can get a list of all trades they have been involved in? Like the list of trade IDs? We have not defined such a function in the chaincode, but you can do so yourself by using the shim API (https://godoc.org/github.com/hyperledger/fabric/core/chaincode/shim). In particular, check out the functions `GetStateByPartialCompositeKey` and `GetStateByRange`. You can write, for example, a function `getTradeIDList` in which you use `GetStateByPartialCompositeKey` with the `Trade` prefix to get the trade ID list.

A client must enroll with a particular Fabric CA instance in our example application, where each CA instance is uniquely associated with a given organization. If you examine the chaincode (`tradeWorkflow.go`), you will see that only the organization name matters, and it is used to control access to the individual functions. In the web `application`, there is another layer of identity, involving login IDs, but those are interpreted only by the web server and are invisible to the chaincode, which only cares about organization membership.

Does this answer your questions?

**Comment by bh4rtp** [comment]
Thanks. I got your points. It sounds reasonable. About question 1, yes I want to do a compound query. And I agree with you about the web application to deal with another layer of login IDs.

**Comment by bh4rtp** [comment]
I am sorry. Still doubted about how to get all involved transactions of importer `ImpEx` for example. As you said, we can know `ImpEx`'s MSP is `ImporterOrgMSP`. Do you mean I can implement a function like `getTransactions('ImportedOrgMSP', 'ImpEx')` to do get states by range? Now the MSP and importer name are given by client. Why need the chaincode instantiated with args as args in `Init`? 
Thanks.

**Comment by bh4rtp** [comment]
Thanks. Clear now.
