### ISSUE TITLE
run the server

### ISSUE THREAD

**Issue by soheiloo** [HyperledgerHandsOn/trade-finance-logistics#37]
hey ,

who with witch ablility could run this software?

it is important to know ,who I gave this program to setup?

i'll be glad if answer me asap .

**Comment by VRamakrishna** [comment]
Just to run it based on the default instructions hardly requires much skill. But to understand what's going on, and tweak or debug the code, I'd say you need any developer who has basic familiarity with docker, git, Linux shell scripting, Go language, JavaScript, and web programming. Also, basic knowledge of blockchain and in particular Hyperledger Fabric (which you can get from our book, as well as from the online documentation.)

**Comment by soheiloo** [comment]
Thanks for your responde,

how can we integrate it by erp ?

witch is better way to use it as an module ?

consider we will assign customer as importer and other organizations as companeis .
