### ISSUE TITLE
Implementation of BFT consensus in hyperledger fabric

### ISSUE THREAD

**Issue by nizamk** [HyperledgerHandsOn/trade-finance-logistics#38]
Hi,

I try to understand from the book and exercises on understanding implementation of BFT consensus in hyperledger. So far i don't find any satisfactory explanations. I've found the explanation in the book is rather brief or i have misunderstood something. Could you give some pointers on this?

thanks.

**Comment by VRamakrishna** [comment]
A blockchain can use any consensus mechanism that offers the desired level of assurance. A blockchain doesn't have to be tied to any particular mechanisms, like BFT for example. If all that is desired is crash fault tolerance, one can use RAFT.

The book tries to discuss blockchain concepts, and not consensus concepts, which, though used by blockchains, are somewhat orthogonal to the main topic. Where BFT finds an application is in the ordering service. If you have more than one ordering service node, each belonging to a different organization, they could run BFT consensus to settle on a transaction ordering within a block. At some point, this feature might be available in Hyperledger Fabric, so you should keep following the (open source) project's progress.
