### ISSUE TITLE
cryptogen: command not found

### ISSUE THREAD

**Issue by sugamxp** [HyperledgerHandsOn/trade-finance-logistics#41]
sugamxp@sugamxp:~/go/src/trade-finance-logistics/network$ cryptogen generate --config=./crypto-config.yaml
cryptogen: command not found
 
Please help

**Comment by VRamakrishna** [comment]
Please download and build Fabric first. Look at the prerequisites section for instructions: https://github.com/HyperledgerHandsOn/trade-finance-logistics/tree/master/network.
