### ISSUE TITLE
Cannot read property 'stack' of undefined

### ISSUE THREAD

**Issue by naqvijafar91** [HyperledgerHandsOn/trade-finance-logistics#49]
I am facing this issue when running node createTradeapp,js after starting the network using trade.sh,

please find the attached screenshot, here is the stack trace:

info: [ClientUtils]: 

*******************************************************************************
*******************************************************************************
*                                          
* Using temp dir: ../network/client-certs
*                                          
*******************************************************************************
*******************************************************************************

Successfully extracted the config update from the configtx envelope
Successfully enrolled user 'admin' for exporterorg
Successfully signed config as admin of exporterorg
Successfully enrolled user 'admin' for importerorg
Successfully signed config as admin of importerorg
Successfully enrolled user 'admin' for carrierorg
Successfully signed config as admin of carrierorg
Successfully enrolled user 'admin' for regulatororg
Successfully signed config as admin of regulatororg
Successfully enrolled user 'admin' for every org and obtained channel config signatures
Successfully enrolled user 'admin' for orderer
error: [Orderer.js]: sendDeliver - rejecting - status:NOT_FOUND
Channel tradechannel does not exist yet (IGNORE ANY ORDERER ERROR MESSAGES YOU SEE ABOVE!!)
Successfully signed config update as orderer admin
Successfully created the channel.
Successfully waited to make sure new channel was created.

--------------------------
CHANNEL CREATION COMPLETE
--------------------------

Joining channel tradechannel
Successfully enrolled 'admin' user for org exporterorg
Successfully got the genesis block
E0130 18:27:21.610882542   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0130 18:27:21.611012146   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/home/syed/go/src/github.com/naqvijafar91/digipramaan/middleware/node_modules/grpc/src/client.js:64:15)
    at /home/syed/go/src/github.com/naqvijafar91/digipramaan/middleware/node_modules/grpc/src/client.js:583:15
E0130 18:27:22.612312296   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0130 18:27:24.264777422   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0130 18:27:26.866948386   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0130 18:27:30.193909661   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0130 18:27:35.872063050   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0130 18:27:45.935098922   13988 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
undefined
Failed join attempt: TypeError: Cannot read property 'stack' of undefined
    at Client.newDefaultKeyValueStore.then.then.then.then (/home/syed/go/src/github.com/naqvijafar91/digipramaan/middleware/join-channel.js:206:61)
    at <anonymous>
![createtradeapperror](https://user-images.githubusercontent.com/13377690/51982900-42d22d00-24bd-11e9-9bd3-c172f0c5581e.png)

**Comment by VRamakrishna** [comment]
Looks like you have old/mismatched credentials lying around. Delete your `client-certs` folder and retry. If you want to start from scratch, delete channel and crypto artifacts, and also the running docker containers and volumes.

A similar error is being tracked in https://github.com/HyperledgerHandsOn/trade-finance-logistics/issues/48, so I'm closing this for now. You can continue commenting on that thread.
