### ISSUE TITLE
Problem in running the app

### ISSUE THREAD

**Issue by kaliaanup** [HyperledgerHandsOn/trade-finance-logistics#52]
I have completed the network part followed by the middleware part. Then I am trying to run the application by running "node app.js", however I am getting the following error.

$node app.js

info: [ClientUtils]: 

*******************************************************************************
*******************************************************************************
*                                          
* Using temp dir: ../network/client-certs
*                                          
*******************************************************************************
*******************************************************************************

[2019-02-10 10:55:45.299] [INFO] TradeApp - ****************** SERVER STARTED ************************
[2019-02-10 10:55:45.300] [INFO] TradeApp - ***************  http://localhost:4000  ******************
UnauthorizedError: No authorization token was found

**Comment by VRamakrishna** [comment]
What query did you send to the server that triggered this error?

**Comment by kaliaanup** [comment]
Just tried to invoke the url (http://localhost:4000) on a browser.

**Comment by VRamakrishna** [comment]
Ah, I agree that ought to be handled more gracefully, but just hitting the web server like that serves no purpose. Try the queries that hit the blockchain and do something useful. A sample list is given in the README here and in the book.

**Comment by kaliaanup** [comment]
I think the issue is resolved. I am able to run curl commands.
