### ISSUE TITLE
Error while setting up network

### ISSUE THREAD

**Issue by mrahman14** [HyperledgerHandsOn/trade-finance-logistics#55]
I'm trying to set up the network part.
I ran docker-compose -f docker-compose-e2e-template.yaml up but I receive the following errors:

**ca_peerImporterOrg              | Error: File specified by 'tls.keyfile' do
t exist: /etc/hyperledger/fabric-ca-server-config/IMPORTER_CA_PRIVATE_KEY
ca_peerExporterOrg              | Error: File specified by 'tls.keyfile' do
t exist: /etc/hyperledger/fabric-ca-server-config/EXPORTER_CA_PRIVATE_KEY
ca_peerRegulatorOrg             | Error: File specified by 'tls.keyfile' do
t exist: /etc/hyperledger/fabric-ca-server-config/REGULATOR_CA_PRIVATE_KEY**

Did anyone have the same issue? How to solve this?
I just need to get the app running without any modification.

Thanks in advance!

**Comment by VRamakrishna** [comment]
What platform are you running this on? (The default code and instructions are for Linux Bash, though there are instructions given in the book for Macs too.) Strings like `IMPORTER_CA_PRIVATE_KEY` are environment variables that are substituted with real filenames when you run the `trade.sh generate` command. If you are running on a bash shell in Linux, you should not get the above error. If it's a Mac, change the code based on what's in the book. If it's anything else, you'll just have to figure out how to make the substitutions. See (and adapt) the code in `network/trade.sh`.

**Comment by VRamakrishna** [comment]
Should be fixed with https://github.com/HyperledgerHandsOn/trade-finance-logistics/commit/da0d715c9c22b989a0e5da20da496068652b92f7
