### ISSUE TITLE
Issue with "--with-default-names"

### ISSUE THREAD

**Issue by jkm5ef** [HyperledgerHandsOn/trade-finance-logistics#61]
I am having trouble with the "brew install gnu-tar --with-default-names command". When I run it, I get the error "Error: invalid option: --with-default-names". Subsequently, when I attempt to run the "make docker" command to build images for various network components, I get the following error:
 
Building docker peer-image
docker build  -t hyperledger/fabric-peer .build/image/peer
Sending build context to Docker daemon  33.41MB
Step 1/7 : FROM hyperledger/fabric-baseos:amd64-0.4.14
 ---> 75f5fb1a0e0c
Step 2/7 : ENV FABRIC_CFG_PATH /etc/hyperledger/fabric
 ---> Using cache
 ---> ea76af896881
Step 3/7 : RUN mkdir -p /var/hyperledger/production $FABRIC_CFG_PATH
 ---> Using cache
 ---> 89ba02a093ab
Step 4/7 : COPY payload/peer /usr/local/bin
 ---> Using cache
 ---> 7e2225b8badd
Step 5/7 : ADD  payload/sampleconfig.tar.bz2 $FABRIC_CFG_PATH
failed to copy files: Error processing tar file(bzip2 data invalid: bad magic value in continuation file):
make: *** [.build/image/peer/.dummy-amd64-1.4.1-snapshot-02dace615] Error 1

**Comment by jkm5ef** [comment]
Got it, needed to manually add a "gnubin" directory to the PATH
 PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"

**Comment by VRamakrishna** [comment]
Thank you.
