### ISSUE TITLE
generateCert function's sed command issue for osx.

### ISSUE THREAD

**Issue by bosoa** [HyperledgerHandsOn/trade-finance-logistics#62]
ISSUE: When running ./trade.sh generate -c tradechannel command for testing, I found sed command has issue on osx. 

SOLVE: change [sed -i] with [sed -i ""].

REASON: Unlike Ubuntu, OS X requires the extension to be explicitly specified. The workaround is to set an empty string: 
$ sed -i '' 's/megatron/pony/g' /path/to/file.txt
 (ref: https://github.com/lmquang/til/issues/18)

**Comment by VRamakrishna** [comment]
Fixed with https://github.com/HyperledgerHandsOn/trade-finance-logistics/commit/da0d715c9c22b989a0e5da20da496068652b92f7
