### ISSUE TITLE
./startFabric.sh Failed to generate orderer genesis block...

### ISSUE THREAD

**Issue by zhengfengyi** [HyperledgerHandsOn/trade-finance-logistics#73]
$ ../bin/configtxgen -version
configtxgen:
 Version: 2.0.0
 Commit SHA: 0432c3e80
 Go version: go1.13.4
 OS/Arch: windows/amd64

byfn.sh not change why the ./startFabric.sh the conmands not have -profile args

$ ./startFabric.sh
+ export MSYS_NO_PATHCONV=1
+ MSYS_NO_PATHCONV=1
++ date +%s
+ starttime=1588070575
+ CC_SRC_LANGUAGE=go
++ echo go
++ tr '[:upper:]' '[:lower:]'
+ CC_SRC_LANGUAGE=go
+ '[' go = go -o go = golang ']'
+ CC_RUNTIME_LANGUAGE=golang
+ CC_SRC_PATH=github.com/hyperledger/fabric-samples/chaincode/fabcar/go
+ echo Vendoring Go dependencies ...
Vendoring Go dependencies ...
+ pushd ../chaincode/fabcar/go
/d/fabric/fabric-samples/chaincode/fabcar/go /d/fabric/fabric-samples/fabcar
+ GO111MODULE=on
+ go mod vendor
+ popd
/d/fabric/fabric-samples/fabcar
+ echo Finished vendoring Go dependencies
Finished vendoring Go dependencies
+ rm -rf ./hfc-key-store
+ pushd ../first-network
/d/fabric/fabric-samples/first-network /d/fabric/fabric-samples/fabcar
+ echo y
+ ./byfn.sh down
Stopping for channel 'mychannel' with CLI timeout of '10' seconds and CLI delay of '3' seconds
proceeding ...
The BYFN_CA1_PRIVATE_KEY variable is not set. Defaulting to a blank string.
The BYFN_CA2_PRIVATE_KEY variable is not set. Defaulting to a blank string.
Removing network net_byfn
Network net_byfn not found.
Removing volume net_orderer.example.com
Volume net_orderer.example.com not found.
Removing volume net_peer0.org1.example.com
Volume net_peer0.org1.example.com not found.
Removing volume net_peer1.org1.example.com
Volume net_peer1.org1.example.com not found.
Removing volume net_peer0.org2.example.com
Volume net_peer0.org2.example.com not found.
Removing volume net_peer1.org2.example.com
Volume net_peer1.org2.example.com not found.
Removing volume net_orderer2.example.com
Volume net_orderer2.example.com not found.
Removing volume net_orderer3.example.com
Volume net_orderer3.example.com not found.
Removing volume net_orderer4.example.com
Volume net_orderer4.example.com not found.
Removing volume net_orderer5.example.com
Volume net_orderer5.example.com not found.
Removing volume net_peer0.org3.example.com
Volume net_peer0.org3.example.com not found.
Removing volume net_peer1.org3.example.com
Volume net_peer1.org3.example.com not found.
---- No containers available for deletion ----
---- No images available for deletion ----
+ echo y
+ ./byfn.sh up -a -n -s couchdb

Starting for channel 'mychannel' with CLI timeout of '10' seconds and CLI delay of '3' seconds and using database 'couchdb'
proceeding ...
LOCAL_VERSION=2.0.0
DOCKER_IMAGE_VERSION=2.0.0
/d/fabric/fabric-samples/bin/cryptogen

##########################################################
##########################################################
+ cryptogen generate --config=./crypto-config.yaml
org1.example.com
org2.example.com
+ res=0
+ set +x

Generate CCP files for Org1 and Org2
/d/fabric/fabric-samples/bin/configtxgen
##########################################################
##########################################################
2020-04-28 18:43:08.035 CST [common.tools.configtxgen] main -> INFO 001 Loading configuration
2020-04-28 18:43:08.054 CST [common.tools.configtxgen.localconfig] Load -> PANI 002 Error reading configuration:  Unsupported Config Type ""
2020-04-28 18:43:08.054 CST [common.tools.configtxgen] func1 -> PANI 003 Error reading configuration:  Unsupported Config Type ""
panic: Error reading configuration:  Unsupported Config Type "" [recovered]
        panic: Error reading configuration:  Unsupported Config Type ""

goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000b1e40, 0x0, 0x0, 0x0)
        /__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x54d
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0001a8188, 0x4, 0xc00002d280, 0x38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x107
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0001a8190, 0xc0003638e8, 0x1, 0x1)
        /__w/1/go/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0xa0
main.main.func1()
        /__w/1/go/src/github.com/hyperledger/fabric/cmd/configtxgen/main.go:253 +0x17d
panic(0xa04cc0, 0xc000352e40)
        /usr/local/go/src/runtime/panic.go:679 +0x1c0
github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000b1e40, 0x0, 0x0, 0x0)
        /__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x54d
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0001a8168, 0x4, 0xc00002d180, 0x38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x107
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)
        /__w/1/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0001a8170, 0xc000363cd8, 0x2, 0x2)
        /__w/1/go/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0xa0
github.com/hyperledger/fabric/internal/configtxgen/genesisconfig.Load(0xc000030520, 0x17, 0x0, 0x0, 0x0, 0x0)
        /__w/1/go/src/github.com/hyperledger/fabric/internal/configtxgen/genesisconfig/config.go:253 +0x22f
main.main()
        /__w/1/go/src/github.com/hyperledger/fabric/cmd/configtxgen/main.go:268 +0xf4c
Failed to generate orderer genesis block...

**Comment by VRamakrishna** [comment]
Wrong repo. For BYFN questions, please use the Hyperledger Fabric mailing list (or rocket chat).
